// src/app/about/about.component.ts
import { Component, ElementRef, OnInit, ViewChild } from '@angular/core';
import { CommonModule } from '@angular/common';
import { EducationService } from '../education.service';
import { ExperienceService } from '../experience.service';
import { environment } from '../../environments/environment';

@Component({
  selector: 'app-about',
  imports: [CommonModule],
  templateUrl: './about.component.html',
  styleUrl: './about.component.css'
})
export class AboutComponent implements OnInit {
  @ViewChild('experienceElement') experienceElement?: ElementRef;
  @ViewChild('educationElement') educationElement?: ElementRef;


  experiences: any[] = [];

  educations: any[] = [];

  constructor(private educationService: EducationService, private experienceService: ExperienceService) { }

  ngOnInit(): void {
    this.getExperience();
    this.getEducation();
  }

  getEducation() {
    this.educationService.getEducations().subscribe({
      next: (educations) => {
        this.educations = educations;
      },
      error: (error) => {
        console.log(error);
      }
    });
  }

  getExperience() {
    this.experienceService.getExperiences().subscribe({
      next: (experiences) => {
        this.experiences = experiences;
      },
      error: (error) => {
        console.log(error);
      }
    });
  }

  downloadResume(): void {
    const resumeUrl = 'assets/resume/Kai_Taing_Resume.pdf';
    const link = document.createElement('a');
    link.href = resumeUrl;
    link.download = 'Kai_Taing_Resume.pdf';

    link.click();
  }

  scrollToExperience(): void {
    if (this.experienceElement) {
      this.experienceElement.nativeElement.scrollIntoView({ behavior: 'smooth' });
    }
  }

  scrollToEducation(): void {
    if (this.educationElement) {
      this.educationElement.nativeElement.scrollIntoView({ behavior: 'smooth' });
    }
  }
}

<section class="about-me">
    <div class="content">
        <h2>About <span>Me</span></h2>
        <p>I'm passionate about staying up-to-date with the latest technologies and trends, ensuring my skills remain
            relevant and effective. With a strong foundation in computer science and a drive to continuously learn, I'm
            committed to delivering high-quality solutions that meet the evolving needs of businesses and organizations.
        </p>

        <div class="btn-group">
            <a (click)="downloadResume()" class=" download-resume">Resume</a>
            <a (click)="scrollToExperience()" class="experience-btn">Experience</a>
        </div>
    </div>
</section>

<section class="experience" #experienceElement>
    <div class="content">
        <h2>Experience</h2>
        <ul>
            <li *ngFor="let experience of experiences">
                <h4>{{ experience.role }} - {{ experience.company }}</h4>
                <p>{{ experience.description }}</p>
            </li>
        </ul>
        <div class="btn-group">
            <a (click)="scrollToEducation()" class="education-btn">Education</a>
        </div>
    </div>
</section>

<section class="education" #educationElement>
    <div class="content">
        <h2>Education</h2>
        <ul>
            <li *ngFor="let education of educations">
                <h4>{{ education.degree }} - {{ education.university }}</h4>
                <p>{{ education.description }}</p>
            </li>
        </ul>
    </div>
</section>

// src/components/About/About.tsx
import styles from "./About.module.css";

export default function About() {
  return (
    <section id="about" className={`${styles.aboutSection} container`}>
      <div className={styles.center}>
        <div className={styles.intro}>
          <h1 className={styles.title}>About</h1>
          <p className={styles.lead}>
            I'm passionate about staying up-to-date with the latest technologies
            and trends, ensuring my skills remain relevant and effective. With a
            strong foundation in computer science and a drive to continuously
            learn, I'm committed to delivering high-quality solutions that meet
            the evolving needs of businesses and organizations.
          </p>
          <div className={styles.actions}>
            <button
              type="button"
              className={styles.primary}
              onClick={() => {
                const el = document.getElementById("contact");
                if (el) el.scrollIntoView({ behavior: "smooth" });
              }}
            >
              Contact
            </button>
            <a
              href="/resume.pdf"
              className={styles.primary}
              download="Kai_Taing_Resume.pdf"
              style={{ marginLeft: 12 }}
            >
              Download Resume
            </a>
          </div>
        </div>
      </div>
    </section>
  );
}
